//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.16 at 11:50:14 ���� CST 
//

package com.ics.tcg.web.workflow.client.data;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class Client_Workflow implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7042618199169571423L;
	protected List<Client_Node> hasNodes;
	protected Client_Node hasFirstNode;
	protected Client_Node hasLastNode;
	protected ArrayList<Client_Node> lastNodes = new ArrayList<Client_Node>();
	protected boolean isDone;
	protected boolean lock;

	public boolean isLock() {
		return lock;
	}

	public void setLock(boolean lock) {
		this.lock = lock;
	}

	public ArrayList<Client_Node> getLastNodes() {
		return lastNodes;
	}

	public void setLastNodes(ArrayList<Client_Node> lastNodes) {
		this.lastNodes = lastNodes;
	}

	public boolean isDone() {
		return isDone;
	}

	public void setDone(boolean isDone) {
		this.isDone = isDone;
	}

	public List<Client_Node> getHasNodes() {
		if (hasNodes == null) {
			hasNodes = new ArrayList<Client_Node>();
		}
		return this.hasNodes;
	}

	public Client_Node getHasFirstNode() {
		return hasFirstNode;
	}

	public void setHasFirstNode(Client_Node value) {
		this.hasFirstNode = value;
	}

	public Client_Node getHasLastNode() {
		return hasLastNode;
	}

	public void setHasLastNode(Client_Node hasLastNode) {
		this.hasLastNode = hasLastNode;
	}
}
