//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.16 at 11:50:14 ���� CST 
//

package com.ics.tcg.web.workflow.client.data;

import java.io.Serializable;

public class Client_FaultOutputPort extends Client_Port implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4788193039934584566L;
	public Client_Node belongTo;

	public Client_Node getBelongTo() {
		return belongTo;
	}

	public void setBelongTo(Client_Node belongTo) {
		this.belongTo = belongTo;
	}
}
