//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.16 at 11:50:14 ���� CST 
//

package com.ics.tcg.web.workflow.client.data;

import java.util.ArrayList;
import java.util.List;

public class Client_OutputPort extends Client_Port {

	/**
	 * 
	 */
	private static final long serialVersionUID = -950302960145002365L;
	public Client_Node belongTo;
	public List<Client_Node> hasNextNodes;

	public Client_Node getBelongTo() {
		return belongTo;
	}

	public void setBelongTo(Client_Node value) {
		this.belongTo = value;
	}

	public List<Client_Node> getHasNextNodes() {
		if (hasNextNodes == null) {
			hasNextNodes = new ArrayList<Client_Node>();
		}
		return this.hasNextNodes;
	}

}
