//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.16 at 11:50:14 ���� CST 
//

package com.ics.tcg.web.workflow.client.data;

import java.io.Serializable;

import com.ics.tcg.web.workflow.server.service.javadescription.DataType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;choice&gt;
 *         &lt;element name=&quot;operation_input&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;attribute name=&quot;serviceName&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anySimpleType&quot; /&gt;
 *                 &lt;attribute name=&quot;operationName&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anySimpleType&quot; /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name=&quot;userInput&quot; type=&quot;{}typesType&quot;/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name=&quot;name&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;isSelected&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}boolean&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

public class Client_Operation implements Serializable {


	private static final long serialVersionUID = 4975056361991030855L;
	protected Client_Operation.Client_FromService fromService;
	protected Client_DataType fromUser;
	protected String operationName;

	/**
	 * Gets the value of the fromService property.
	 * 
	 * @return possible object is {@link Server_Operation.FromService }
	 * 
	 */
	public Client_Operation.Client_FromService getFromService() {
		return fromService;
	}

	/**
	 * Sets the value of the fromService property.
	 * 
	 * @param value
	 *            allowed object is {@link Server_Operation.FromService }
	 * 
	 */
	public void setFromService(Client_Operation.Client_FromService value) {
		this.fromService = value;
	}

	/**
	 * Gets the value of the fromUser property.
	 * 
	 * @return possible object is {@link DataType }
	 * 
	 */
	public Client_DataType getFromUser() {
		return fromUser;
	}

	/**
	 * Sets the value of the fromUser property.
	 * 
	 * @param value
	 *            allowed object is {@link DataType }
	 * 
	 */
	public void setFromUser(Client_DataType value) {
		this.fromUser = value;
	}

	/**
	 * Gets the value of the operationName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOperationName() {
		return operationName;
	}

	/**
	 * Sets the value of the operationName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOperationName(String value) {
		this.operationName = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;attribute name=&quot;serviceName&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anySimpleType&quot; /&gt;
	 *       &lt;attribute name=&quot;operationName&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anySimpleType&quot; /&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	public static class Client_FromService {

		protected String serviceName;
		protected String operationName;

		/**
		 * Gets the value of the serviceName property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getServiceName() {
			return serviceName;
		}

		/**
		 * Sets the value of the serviceName property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setServiceName(String value) {
			this.serviceName = value;
		}

		/**
		 * Gets the value of the operationName property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getOperationName() {
			return operationName;
		}

		/**
		 * Sets the value of the operationName property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setOperationName(String value) {
			this.operationName = value;
		}

	}

}
