//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.16 at 11:50:14 ���� CST 
//

package com.ics.tcg.web.workflow.client.data;

import java.io.Serializable;

import com.ics.tcg.web.workflow.client.service.ServiceInfo;

public class Client_Service implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1064610814657549942L;
	protected Client_ServiceDescription hasDesciption;
	protected Client_QosRequirement hasQosRequirement;
	protected Client_Configuration hasConfiguration;
	private ServiceInfo serviceInfo; // 服务信息，包括服务配置部分也保存到了服务信息的每个方法的输入参数当中

	// protected String serviceName;

	public Client_ServiceDescription getHasDesciption() {
		return hasDesciption;
	}

	public void setHasDesciption(Client_ServiceDescription value) {
		this.hasDesciption = value;
	}

	public Client_QosRequirement getHasQosRequirement() {
		return hasQosRequirement;
	}

	public void setHasQosRequirement(Client_QosRequirement value) {
		this.hasQosRequirement = value;
	}

	public Client_Configuration getHasConfiguration() {
		return hasConfiguration;
	}

	public void setHasConfiguration(Client_Configuration value) {
		this.hasConfiguration = value;
	}

	public ServiceInfo getServiceInfo() {
		return serviceInfo;
	}

	public void setServiceInfo(ServiceInfo serviceInfo) {
		this.serviceInfo = serviceInfo;
	}

	// public String getServiceName() {
	// return serviceName;
	// }
	//
	// public void setServiceName(String value) {
	// this.serviceName = value;
	// }

}
